application: breadboard-site
version: 7
runtime: python
api_version: 1

handlers:

 
- url: /media
  static_dir: media
  
- url: /sandbox
  static_dir: sandbox
  
- url: /sandbox/.*
  script: sandbox.py
  #login: admin

- url: /.*
  script: main.py

builtins:
- datastore_admin: on
