application: breadboard-site
version: 7
runtime: python
api_version: 1

handlers:

 
- url: /media
  static_dir: media
  
- url: /sandbox
  static_dir: sandbox

# only for mobile test
- url: /mobile_views
  static_dir: mobile_views


- url: /poll
  script: poll.py
  
- url: /test/.*
  script: test.py
  #login: admin

- url: /.*
  script: main.py

builtins:
- datastore_admin: on
