application: protoboard-site
version: 7
runtime: python
api_version: 1

handlers:
- url: /robots.txt
  static_files: media/robots.txt
  upload: media/robots.txt

#- url: /sitemap.xml
#  static_files: media/sitemap.xml
#  upload: media/sitemap.xml
 
- url: /media
  static_dir: media
  
- url: /sandbox
  static_dir: sandbox

- url: /keynotes
  static_dir: keynotes

- url: /sandbox/.*
  script: sandbox.py
  #login: admin

- url: /.*
  script: main.py

builtins:
- datastore_admin: on
