application: protoboard-site
version: 7
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /robots.txt
  static_files: media/robots.txt
  upload: media/robots.txt

#- url: /sitemap.xml
#  static_files: media/sitemap.xml
#  upload: media/sitemap.xml
 
- url: /media
  static_dir: media
  
- url: /sandbox_files
  static_dir: sandbox

- url: /keynotes
  static_dir: keynotes

- url: /sandbox/.*
  script: sandbox.app
  #login: admin

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest

builtins:
- datastore_admin: on
- appstats: on